// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package gvm

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_ShardBlock            protoreflect.MessageDescriptor
	fd_ShardBlock_index      protoreflect.FieldDescriptor
	fd_ShardBlock_parent     protoreflect.FieldDescriptor
	fd_ShardBlock_leftChild  protoreflect.FieldDescriptor
	fd_ShardBlock_rightChild protoreflect.FieldDescriptor
	fd_ShardBlock_vdf        protoreflect.FieldDescriptor
)

func init() {
	file_gvm_gvm_shard_block_proto_init()
	md_ShardBlock = File_gvm_gvm_shard_block_proto.Messages().ByName("ShardBlock")
	fd_ShardBlock_index = md_ShardBlock.Fields().ByName("index")
	fd_ShardBlock_parent = md_ShardBlock.Fields().ByName("parent")
	fd_ShardBlock_leftChild = md_ShardBlock.Fields().ByName("leftChild")
	fd_ShardBlock_rightChild = md_ShardBlock.Fields().ByName("rightChild")
	fd_ShardBlock_vdf = md_ShardBlock.Fields().ByName("vdf")
}

var _ protoreflect.Message = (*fastReflection_ShardBlock)(nil)

type fastReflection_ShardBlock ShardBlock

func (x *ShardBlock) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ShardBlock)(x)
}

func (x *ShardBlock) slowProtoReflect() protoreflect.Message {
	mi := &file_gvm_gvm_shard_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ShardBlock_messageType fastReflection_ShardBlock_messageType
var _ protoreflect.MessageType = fastReflection_ShardBlock_messageType{}

type fastReflection_ShardBlock_messageType struct{}

func (x fastReflection_ShardBlock_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ShardBlock)(nil)
}
func (x fastReflection_ShardBlock_messageType) New() protoreflect.Message {
	return new(fastReflection_ShardBlock)
}
func (x fastReflection_ShardBlock_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ShardBlock
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ShardBlock) Descriptor() protoreflect.MessageDescriptor {
	return md_ShardBlock
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ShardBlock) Type() protoreflect.MessageType {
	return _fastReflection_ShardBlock_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ShardBlock) New() protoreflect.Message {
	return new(fastReflection_ShardBlock)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ShardBlock) Interface() protoreflect.ProtoMessage {
	return (*ShardBlock)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ShardBlock) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Index)
		if !f(fd_ShardBlock_index, value) {
			return
		}
	}
	if x.Parent != "" {
		value := protoreflect.ValueOfString(x.Parent)
		if !f(fd_ShardBlock_parent, value) {
			return
		}
	}
	if x.LeftChild != "" {
		value := protoreflect.ValueOfString(x.LeftChild)
		if !f(fd_ShardBlock_leftChild, value) {
			return
		}
	}
	if x.RightChild != "" {
		value := protoreflect.ValueOfString(x.RightChild)
		if !f(fd_ShardBlock_rightChild, value) {
			return
		}
	}
	if x.Vdf != "" {
		value := protoreflect.ValueOfString(x.Vdf)
		if !f(fd_ShardBlock_vdf, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ShardBlock) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "gvm.gvm.ShardBlock.index":
		return x.Index != uint64(0)
	case "gvm.gvm.ShardBlock.parent":
		return x.Parent != ""
	case "gvm.gvm.ShardBlock.leftChild":
		return x.LeftChild != ""
	case "gvm.gvm.ShardBlock.rightChild":
		return x.RightChild != ""
	case "gvm.gvm.ShardBlock.vdf":
		return x.Vdf != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ShardBlock) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "gvm.gvm.ShardBlock.index":
		x.Index = uint64(0)
	case "gvm.gvm.ShardBlock.parent":
		x.Parent = ""
	case "gvm.gvm.ShardBlock.leftChild":
		x.LeftChild = ""
	case "gvm.gvm.ShardBlock.rightChild":
		x.RightChild = ""
	case "gvm.gvm.ShardBlock.vdf":
		x.Vdf = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ShardBlock) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "gvm.gvm.ShardBlock.index":
		value := x.Index
		return protoreflect.ValueOfUint64(value)
	case "gvm.gvm.ShardBlock.parent":
		value := x.Parent
		return protoreflect.ValueOfString(value)
	case "gvm.gvm.ShardBlock.leftChild":
		value := x.LeftChild
		return protoreflect.ValueOfString(value)
	case "gvm.gvm.ShardBlock.rightChild":
		value := x.RightChild
		return protoreflect.ValueOfString(value)
	case "gvm.gvm.ShardBlock.vdf":
		value := x.Vdf
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ShardBlock) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "gvm.gvm.ShardBlock.index":
		x.Index = value.Uint()
	case "gvm.gvm.ShardBlock.parent":
		x.Parent = value.Interface().(string)
	case "gvm.gvm.ShardBlock.leftChild":
		x.LeftChild = value.Interface().(string)
	case "gvm.gvm.ShardBlock.rightChild":
		x.RightChild = value.Interface().(string)
	case "gvm.gvm.ShardBlock.vdf":
		x.Vdf = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ShardBlock) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gvm.gvm.ShardBlock.index":
		panic(fmt.Errorf("field index of message gvm.gvm.ShardBlock is not mutable"))
	case "gvm.gvm.ShardBlock.parent":
		panic(fmt.Errorf("field parent of message gvm.gvm.ShardBlock is not mutable"))
	case "gvm.gvm.ShardBlock.leftChild":
		panic(fmt.Errorf("field leftChild of message gvm.gvm.ShardBlock is not mutable"))
	case "gvm.gvm.ShardBlock.rightChild":
		panic(fmt.Errorf("field rightChild of message gvm.gvm.ShardBlock is not mutable"))
	case "gvm.gvm.ShardBlock.vdf":
		panic(fmt.Errorf("field vdf of message gvm.gvm.ShardBlock is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ShardBlock) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gvm.gvm.ShardBlock.index":
		return protoreflect.ValueOfUint64(uint64(0))
	case "gvm.gvm.ShardBlock.parent":
		return protoreflect.ValueOfString("")
	case "gvm.gvm.ShardBlock.leftChild":
		return protoreflect.ValueOfString("")
	case "gvm.gvm.ShardBlock.rightChild":
		return protoreflect.ValueOfString("")
	case "gvm.gvm.ShardBlock.vdf":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gvm.gvm.ShardBlock"))
		}
		panic(fmt.Errorf("message gvm.gvm.ShardBlock does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ShardBlock) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in gvm.gvm.ShardBlock", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ShardBlock) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ShardBlock) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ShardBlock) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ShardBlock) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ShardBlock)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Index != 0 {
			n += 1 + runtime.Sov(uint64(x.Index))
		}
		l = len(x.Parent)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LeftChild)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RightChild)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Vdf)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ShardBlock)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Vdf) > 0 {
			i -= len(x.Vdf)
			copy(dAtA[i:], x.Vdf)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Vdf)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.RightChild) > 0 {
			i -= len(x.RightChild)
			copy(dAtA[i:], x.RightChild)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RightChild)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.LeftChild) > 0 {
			i -= len(x.LeftChild)
			copy(dAtA[i:], x.LeftChild)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LeftChild)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Parent) > 0 {
			i -= len(x.Parent)
			copy(dAtA[i:], x.Parent)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Parent)))
			i--
			dAtA[i] = 0x12
		}
		if x.Index != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Index))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ShardBlock)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ShardBlock: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ShardBlock: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				x.Index = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Index |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Parent = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LeftChild", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LeftChild = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RightChild", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RightChild = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Vdf", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Vdf = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: gvm/gvm/shard_block.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index      uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Parent     string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	LeftChild  string `protobuf:"bytes,3,opt,name=leftChild,proto3" json:"leftChild,omitempty"`
	RightChild string `protobuf:"bytes,4,opt,name=rightChild,proto3" json:"rightChild,omitempty"`
	Vdf        string `protobuf:"bytes,5,opt,name=vdf,proto3" json:"vdf,omitempty"`
}

func (x *ShardBlock) Reset() {
	*x = ShardBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gvm_gvm_shard_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardBlock) ProtoMessage() {}

// Deprecated: Use ShardBlock.ProtoReflect.Descriptor instead.
func (*ShardBlock) Descriptor() ([]byte, []int) {
	return file_gvm_gvm_shard_block_proto_rawDescGZIP(), []int{0}
}

func (x *ShardBlock) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ShardBlock) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ShardBlock) GetLeftChild() string {
	if x != nil {
		return x.LeftChild
	}
	return ""
}

func (x *ShardBlock) GetRightChild() string {
	if x != nil {
		return x.RightChild
	}
	return ""
}

func (x *ShardBlock) GetVdf() string {
	if x != nil {
		return x.Vdf
	}
	return ""
}

var File_gvm_gvm_shard_block_proto protoreflect.FileDescriptor

var file_gvm_gvm_shard_block_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x76, 0x6d, 0x2f, 0x67, 0x76, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x76, 0x6d,
	0x2e, 0x67, 0x76, 0x6d, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x69, 0x67, 0x68, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x69, 0x67, 0x68, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x64, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x64,
	0x66, 0x42, 0x75, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x76, 0x6d, 0x2e, 0x67, 0x76, 0x6d,
	0x42, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x18, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x76, 0x6d, 0x2f, 0x67, 0x76, 0x6d, 0xa2, 0x02, 0x03,
	0x47, 0x47, 0x58, 0xaa, 0x02, 0x07, 0x47, 0x76, 0x6d, 0x2e, 0x47, 0x76, 0x6d, 0xca, 0x02, 0x07,
	0x47, 0x76, 0x6d, 0x5c, 0x47, 0x76, 0x6d, 0xe2, 0x02, 0x13, 0x47, 0x76, 0x6d, 0x5c, 0x47, 0x76,
	0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08,
	0x47, 0x76, 0x6d, 0x3a, 0x3a, 0x47, 0x76, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gvm_gvm_shard_block_proto_rawDescOnce sync.Once
	file_gvm_gvm_shard_block_proto_rawDescData = file_gvm_gvm_shard_block_proto_rawDesc
)

func file_gvm_gvm_shard_block_proto_rawDescGZIP() []byte {
	file_gvm_gvm_shard_block_proto_rawDescOnce.Do(func() {
		file_gvm_gvm_shard_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_gvm_gvm_shard_block_proto_rawDescData)
	})
	return file_gvm_gvm_shard_block_proto_rawDescData
}

var file_gvm_gvm_shard_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gvm_gvm_shard_block_proto_goTypes = []interface{}{
	(*ShardBlock)(nil), // 0: gvm.gvm.ShardBlock
}
var file_gvm_gvm_shard_block_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gvm_gvm_shard_block_proto_init() }
func file_gvm_gvm_shard_block_proto_init() {
	if File_gvm_gvm_shard_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gvm_gvm_shard_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gvm_gvm_shard_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gvm_gvm_shard_block_proto_goTypes,
		DependencyIndexes: file_gvm_gvm_shard_block_proto_depIdxs,
		MessageInfos:      file_gvm_gvm_shard_block_proto_msgTypes,
	}.Build()
	File_gvm_gvm_shard_block_proto = out.File
	file_gvm_gvm_shard_block_proto_rawDesc = nil
	file_gvm_gvm_shard_block_proto_goTypes = nil
	file_gvm_gvm_shard_block_proto_depIdxs = nil
}
