// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gvm/shard/to_left_child.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ToLeftChild struct {
	Id     uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender string     `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	Info   string     `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (m *ToLeftChild) Reset()         { *m = ToLeftChild{} }
func (m *ToLeftChild) String() string { return proto.CompactTextString(m) }
func (*ToLeftChild) ProtoMessage()    {}
func (*ToLeftChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2c96dcf7593e2b, []int{0}
}
func (m *ToLeftChild) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ToLeftChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ToLeftChild.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ToLeftChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToLeftChild.Merge(m, src)
}
func (m *ToLeftChild) XXX_Size() int {
	return m.Size()
}
func (m *ToLeftChild) XXX_DiscardUnknown() {
	xxx_messageInfo_ToLeftChild.DiscardUnknown(m)
}

var xxx_messageInfo_ToLeftChild proto.InternalMessageInfo

func (m *ToLeftChild) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToLeftChild) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ToLeftChild) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *ToLeftChild) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*ToLeftChild)(nil), "gvm.shard.ToLeftChild")
}

func init() { proto.RegisterFile("gvm/shard/to_left_child.proto", fileDescriptor_ed2c96dcf7593e2b) }

var fileDescriptor_ed2c96dcf7593e2b = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xbf, 0x4b, 0xc4, 0x30,
	0x1c, 0xc5, 0x9b, 0xb3, 0x14, 0x2e, 0x07, 0x0e, 0x41, 0xa4, 0x1e, 0x18, 0x8b, 0x20, 0x74, 0x31,
	0xe1, 0x74, 0x70, 0x14, 0xee, 0x56, 0xa7, 0xe2, 0xe4, 0x72, 0xf4, 0x47, 0x9a, 0x06, 0x2e, 0xf9,
	0x1e, 0x4d, 0xae, 0xe8, 0xea, 0x5f, 0xe0, 0x9f, 0x75, 0xe3, 0x8d, 0x4e, 0x22, 0xed, 0x3f, 0x22,
	0xfd, 0xe1, 0xf6, 0x92, 0xf7, 0x78, 0x1f, 0xbe, 0x0f, 0x5f, 0xcb, 0x46, 0x73, 0x5b, 0xa5, 0x75,
	0xc1, 0x1d, 0x6c, 0x77, 0xa2, 0x74, 0xdb, 0xbc, 0x52, 0xbb, 0x82, 0xed, 0x6b, 0x70, 0x40, 0xe6,
	0xb2, 0xd1, 0x6c, 0xb0, 0x97, 0x17, 0x12, 0x24, 0x0c, 0xbf, 0xbc, 0x57, 0x63, 0x60, 0x49, 0x73,
	0xb0, 0x1a, 0x2c, 0xcf, 0x52, 0x2b, 0x78, 0xb3, 0xca, 0x84, 0x4b, 0x57, 0x3c, 0x07, 0x65, 0x46,
	0xff, 0xf6, 0x13, 0xe1, 0xc5, 0x2b, 0xbc, 0x88, 0xd2, 0x6d, 0xfa, 0x5a, 0x72, 0x8e, 0x67, 0xaa,
	0x08, 0x51, 0x84, 0x62, 0x3f, 0x99, 0xa9, 0x82, 0x5c, 0xe2, 0xc0, 0x0a, 0x53, 0x88, 0x3a, 0x9c,
	0x45, 0x28, 0x9e, 0x27, 0xd3, 0x8b, 0x3c, 0xe1, 0x20, 0xd5, 0x70, 0x30, 0x2e, 0x3c, 0x8b, 0x50,
	0xbc, 0x78, 0xb8, 0x62, 0x23, 0x88, 0xf5, 0x20, 0x36, 0x81, 0xd8, 0x06, 0x94, 0x59, 0xfb, 0xc7,
	0x9f, 0x1b, 0x2f, 0x99, 0xe2, 0x84, 0x60, 0x5f, 0x99, 0x12, 0x42, 0x7f, 0xa8, 0x1b, 0xf4, 0xfa,
	0xf9, 0xd8, 0x52, 0x74, 0x6a, 0x29, 0xfa, 0x6d, 0x29, 0xfa, 0xea, 0xa8, 0x77, 0xea, 0xa8, 0xf7,
	0xdd, 0x51, 0xef, 0xed, 0x4e, 0x2a, 0x57, 0x1d, 0x32, 0x96, 0x83, 0xe6, 0x12, 0x1a, 0x7d, 0x6f,
	0x84, 0xe3, 0xfd, 0x24, 0xef, 0xff, 0xa3, 0x7c, 0xec, 0x85, 0xcd, 0x82, 0xe1, 0x98, 0xc7, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0xaf, 0xc8, 0x76, 0x2e, 0x01, 0x00, 0x00,
}

func (m *ToLeftChild) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ToLeftChild) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ToLeftChild) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintToLeftChild(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintToLeftChild(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintToLeftChild(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintToLeftChild(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintToLeftChild(dAtA []byte, offset int, v uint64) int {
	offset -= sovToLeftChild(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ToLeftChild) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovToLeftChild(uint64(m.Id))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovToLeftChild(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovToLeftChild(uint64(l))
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovToLeftChild(uint64(l))
	}
	return n
}

func sovToLeftChild(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozToLeftChild(x uint64) (n int) {
	return sovToLeftChild(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ToLeftChild) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToLeftChild
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ToLeftChild: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ToLeftChild: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToLeftChild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToLeftChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthToLeftChild
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthToLeftChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToLeftChild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToLeftChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToLeftChild(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToLeftChild
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipToLeftChild(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowToLeftChild
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToLeftChild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthToLeftChild
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupToLeftChild
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthToLeftChild
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthToLeftChild        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowToLeftChild          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupToLeftChild = fmt.Errorf("proto: unexpected end of group")
)
