// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gvm/shard/to_right_child.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ToRightChild struct {
	Id     uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender string     `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	Info   string     `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (m *ToRightChild) Reset()         { *m = ToRightChild{} }
func (m *ToRightChild) String() string { return proto.CompactTextString(m) }
func (*ToRightChild) ProtoMessage()    {}
func (*ToRightChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1fc61ef63ed7512, []int{0}
}
func (m *ToRightChild) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ToRightChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ToRightChild.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ToRightChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToRightChild.Merge(m, src)
}
func (m *ToRightChild) XXX_Size() int {
	return m.Size()
}
func (m *ToRightChild) XXX_DiscardUnknown() {
	xxx_messageInfo_ToRightChild.DiscardUnknown(m)
}

var xxx_messageInfo_ToRightChild proto.InternalMessageInfo

func (m *ToRightChild) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToRightChild) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ToRightChild) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *ToRightChild) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*ToRightChild)(nil), "gvm.shard.ToRightChild")
}

func init() { proto.RegisterFile("gvm/shard/to_right_child.proto", fileDescriptor_e1fc61ef63ed7512) }

var fileDescriptor_e1fc61ef63ed7512 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x18, 0xc4, 0x9b, 0x5a, 0x0a, 0x1b, 0xc5, 0x43, 0x10, 0xa9, 0x7b, 0x88, 0x45, 0x10, 0x7a, 0x31,
	0x61, 0xf5, 0xe0, 0x51, 0xd8, 0x7d, 0x83, 0xe2, 0xc9, 0xcb, 0xd2, 0x3f, 0x31, 0x0d, 0x98, 0x7c,
	0x4b, 0x93, 0x2d, 0x7a, 0xf6, 0x05, 0x7c, 0xac, 0x3d, 0xee, 0xd1, 0x93, 0x48, 0xfb, 0x22, 0xd2,
	0xb4, 0xde, 0x26, 0x99, 0x61, 0x7e, 0x7c, 0x83, 0xa9, 0xec, 0x34, 0xb7, 0x4d, 0xd1, 0xd6, 0xdc,
	0xc1, 0xb6, 0x55, 0xb2, 0x71, 0xdb, 0xaa, 0x51, 0x6f, 0x35, 0xdb, 0xb5, 0xe0, 0x80, 0x2c, 0x64,
	0xa7, 0x99, 0xf7, 0x97, 0x17, 0x12, 0x24, 0xf8, 0x5f, 0x3e, 0xaa, 0x29, 0xb0, 0xa4, 0x15, 0x58,
	0x0d, 0x96, 0x97, 0x85, 0x15, 0xbc, 0x5b, 0x95, 0xc2, 0x15, 0x2b, 0x5e, 0x81, 0x32, 0x93, 0x7f,
	0xf3, 0x89, 0xf0, 0xd9, 0x33, 0xe4, 0x63, 0xf1, 0x66, 0xec, 0x25, 0xe7, 0x38, 0x54, 0x75, 0x82,
	0x52, 0x94, 0x45, 0x79, 0xa8, 0x6a, 0x72, 0x89, 0x63, 0x2b, 0x4c, 0x2d, 0xda, 0x24, 0x4c, 0x51,
	0xb6, 0xc8, 0xe7, 0x17, 0x79, 0xc4, 0x71, 0xa1, 0x61, 0x6f, 0x5c, 0x72, 0x92, 0xa2, 0xec, 0xf4,
	0xfe, 0x8a, 0x4d, 0x24, 0x36, 0x92, 0xd8, 0x4c, 0x62, 0x1b, 0x50, 0x66, 0x1d, 0x1d, 0x7e, 0xae,
	0x83, 0x7c, 0x8e, 0x13, 0x82, 0x23, 0x65, 0x5e, 0x21, 0x89, 0x7c, 0x9d, 0xd7, 0xeb, 0xa7, 0x43,
	0x4f, 0xd1, 0xb1, 0xa7, 0xe8, 0xb7, 0xa7, 0xe8, 0x6b, 0xa0, 0xc1, 0x71, 0xa0, 0xc1, 0xf7, 0x40,
	0x83, 0x97, 0x5b, 0xa9, 0x5c, 0xb3, 0x2f, 0x59, 0x05, 0x9a, 0x4b, 0xe8, 0xf4, 0x9d, 0x11, 0x8e,
	0x8f, 0xa3, 0xbc, 0xff, 0xcf, 0xf2, 0xb1, 0x13, 0xb6, 0x8c, 0xfd, 0x35, 0x0f, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x68, 0x96, 0x5d, 0xbd, 0x30, 0x01, 0x00, 0x00,
}

func (m *ToRightChild) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ToRightChild) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ToRightChild) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintToRightChild(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintToRightChild(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintToRightChild(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintToRightChild(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintToRightChild(dAtA []byte, offset int, v uint64) int {
	offset -= sovToRightChild(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ToRightChild) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovToRightChild(uint64(m.Id))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovToRightChild(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovToRightChild(uint64(l))
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovToRightChild(uint64(l))
	}
	return n
}

func sovToRightChild(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozToRightChild(x uint64) (n int) {
	return sovToRightChild(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ToRightChild) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToRightChild
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ToRightChild: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ToRightChild: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToRightChild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToRightChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthToRightChild
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthToRightChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToRightChild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToRightChild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToRightChild(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToRightChild
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipToRightChild(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowToRightChild
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToRightChild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthToRightChild
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupToRightChild
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthToRightChild
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthToRightChild        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowToRightChild          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupToRightChild = fmt.Errorf("proto: unexpected end of group")
)
